<?php

declare(strict_types=1);

/**
 *
 * @package    Zalt
 * @subpackage Model\Sql
 * @author     Matijs de Jong <mjong@magnafacta.nl>
 */

namespace Zalt\Model\Sql;

/**
 *
 * @package    Zalt
 * @subpackage Model\Sql
 * @since      Class available since version 1.0
 */
interface SqlRunnerInterface
{
    /**
     * @param mixed $select Something that should be a select statement for this SQL runner
     * @return bool
     */
    public function checkSelect(mixed $select): bool;
    
    /**
     * @param string $tableName
     * @param mixed  $where
     * @return int The number of rows deleted
     */
    public function deleteFromTable(string $tableName, mixed $where): int;

    /**
     * @param string $tableName
     * @param mixed  $where
     * @return array One row of data
     */
    public function fetchRowFromTable(string $tableName, mixed $where): array;

    /**
     * @param string $tableName
     * @param mixed  $where
     * @return array Nested rows of data
     */
    public function fetchRowsFromTable(string $tableName, mixed $where): array;
    
    /**
     * @param string $tableName
     * @param array  $values
     * @return ?int null or last autogenerated insert id
     */
    public function insertInTable(string $tableName, array $values): ?int;

    /**
     * @param string $tableName
     * @param array  $values
     * @param mixed  $where
     * @return int The number of rows updated
     */
    public function updateInTable(string $tableName, array $values, mixed $where): int;
}