<?php

declare(strict_types=1);

/**
 *
 * @package    Zalt
 * @subpackage Model\Sql
 * @author     Matijs de Jong <mjong@magnafacta.nl>
 */

namespace Zalt\Model\Sql;

use Zalt\Model\MetaModelInterface;

/**
 *
 * @package    Zalt
 * @subpackage Model\Sql
 * @since      Class available since version 1.0
 */
interface SqlRunnerInterface
{
    /**
     * @param mixed $select Something that should be a select statement for this SQL runner
     * @return bool
     */
    public function checkSelect(mixed $select): bool;

    public function createSort(MetaModelInterface $metaModel, array $sort): mixed;
    
    /**
     * Check a filter and make sure it works for the SQL version
     * @param MetaModelInterface $metaModel
     * @param mixed $where
     * @return mixed
     */
    public function createWhere(MetaModelInterface $metaModel, mixed $where): mixed;
    
    
    /**
     * @param string $tableName
     * @param mixed  $where
     * @return int The number of rows deleted
     */
    public function deleteFromTable(string $tableName, mixed $where): int;

    /**
     * @param string $tableName
     * @param mixed  $where
     * @return array One row of data
     */
    public function fetchRowFromTable(string $tableName, mixed $where, mixed $sort): array;

    /**
     * @param string $tableName
     * @param mixed  $where
     * @return array Nested rows of data
     */
    public function fetchRowsFromTable(string $tableName, mixed $where, mixed $sort): array;

    /**
     * @param string      $tableName
     * @param string|null $alias
     * @return array name => [settings] for metamodel
     */
    public function getTableMetaData(string $tableName, string $alias = null): array;
 
     /**
     * @param string $tableName
     * @param array  $values
     * @return ?int null or last autogenerated insert id
     */
    public function insertInTable(string $tableName, array $values): ?int;

    /**
     * @param string $tableName
     * @param array  $values
     * @param mixed  $where
     * @return int The number of rows updated
     */
    public function updateInTable(string $tableName, array $values, mixed $where): int;
}